/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "task.h"

bool_t
xdr_task (XDR *xdrs, task *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->payload, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_result (XDR *xdrs, result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->output, 256))
		 return FALSE;
	return TRUE;
}
