/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TASK_H_RPCGEN
#define _TASK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct task {
	int id;
	int type;
	char *payload;
};
typedef struct task task;

struct result {
	int id;
	char *output;
};
typedef struct result result;

#define TASKPROG 0x23451111
#define TASKVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUBMIT_TASK 1
extern  int * submit_task_1(task *, CLIENT *);
extern  int * submit_task_1_svc(task *, struct svc_req *);
#define GET_RESULT 2
extern  result * get_result_1(int *, CLIENT *);
extern  result * get_result_1_svc(int *, struct svc_req *);
extern int taskprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUBMIT_TASK 1
extern  int * submit_task_1();
extern  int * submit_task_1_svc();
#define GET_RESULT 2
extern  result * get_result_1();
extern  result * get_result_1_svc();
extern int taskprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_task (XDR *, task*);
extern  bool_t xdr_result (XDR *, result*);

#else /* K&R C */
extern bool_t xdr_task ();
extern bool_t xdr_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TASK_H_RPCGEN */
